DROP TABLE NEW_INDICATORS;

CREATE TABLE NEW_INDICATORS
  AS (
SELECT * FROM INDICATORS WHERE ROWID IN
    (
        SELECT rid FROM
        (
            SELECT ROWID rid, row_number() OVER(PARTITION BY SYMBOL_ID, CLASS, PARAMETER, ADJUSTMENT_TYPE ORDER BY CALCULATION_DATE DESC) rn
                FROM INDICATORS
        )
        where rn <= 5
    ));

TRUNCATE TABLE INDICATORS;

INSERT INTO INDICATORS SELECT * FROM NEW_INDICATORS;